INSERT INTO COUNTRY VALUES(1, 'Germany')
INSERT INTO COUNTRY VALUES(2, 'India')
INSERT INTO COUNTRY VALUES(3, 'Spain')
INSERT INTO COUNTRY VALUES(4, 'Russia')

INSERT INTO STATE VALUES(1, 1, 'Berlin')
INSERT INTO STATE VALUES(2, 1, 'Munique')

INSERT INTO EMPLOYEE_TYPE VALUES(1, 'Full Time')
INSERT INTO JOB_TITLE VALUES(1, 'Project Manager')

INSERT INTO EMPLOYEE VALUES(1, 1, 'Female', 'Single', 'Nayara Fantin', 1, 1, 1)





